name: Solidity code coverage

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - run: NO_GAS_ENFORCE=1 npx hardhat coverage
